
name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**.MD'
      - 'LICENSE'
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # Uses the version from go.mod (recommended).
          go-version-file: 'go.mod'
          cache: true

      - name: Go version
        run: go version

      - name: Download dependencies
        run: make install

      - name: Generate code
        run: make generate

      - name: Lint
        run: make lint

      - name: Build
        run: make compile

      - name: Test
        run: make test

      - name: Build Docker
        run: docker build -t rm-rf-production .
